-- =====================================================================
-- MSL (My Star League) 전체 DB 초기화 스크립트 (수정 완료 버전)
-- ★ 수정사항
--   1. TBL_BUILDS에 USER_ID / PLAY_STYLE / EXPAND_STYLE / AGGRESSION / TECH_STYLE 컬럼 추가
--   2. INSERT INTO TBL_BUILDS 괄호 누락 오류 수정 (구 new2.sql Line 538)
--   3. 하단 DROP TABLE/SEQUENCE 예외처리 추가 (구 new2.sql Line 633~634)
--   4. 불필요한 임시 테스트 쿼리 / 중간 ALTER / 구버전 빌드 잔재 제거
-- =====================================================================


-- =====================================================================
-- 1. 기존 객체 삭제 (자식 → 부모 순서)
-- =====================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_BATTLE_SESSION';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_OWNED_BUILDS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILD_UNITS';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILDS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_OPPONENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_SUBSTAGE_MAPS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MAPS';                   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_PVE_SUBSTAGE_PROGRESS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_SUBSTAGES';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_PVE_PROGRESS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_ENTRY';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MATCH_RECORDS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MATCH_LOGS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_OWNED_PLAYERS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PACK_CONTENTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PACKS';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PLAYERS';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_USERS CASCADE CONSTRAINTS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PLAYER_BUILDS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 시퀀스 삭제
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAYERS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACKS';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACK_CONTENTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_OWNED_PLAYERS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MATCH_LOGS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MATCH_RECORD';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_ENTRY';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_OPPONENTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_BATTLE_SESSION';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BUILDS';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BUILD_UNITS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_OWNED_BUILDS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAYER_BUILDS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- =====================================================================
-- 2. 시퀀스 생성
-- =====================================================================
CREATE SEQUENCE SEQ_PLAYERS            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PACKS              START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PACK_CONTENTS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OWNED_PLAYERS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATCH_RECORD       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_ENTRY          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_OPPONENTS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_BATTLE_SESSION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BUILDS             START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BUILD_UNITS        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OWNED_BUILDS       START WITH 1 INCREMENT BY 1 NOCACHE;


-- =====================================================================
-- 3. 테이블 생성
-- =====================================================================

-- 1. 사용자
CREATE TABLE TBL_USERS (
    USER_ID     VARCHAR2(50)  PRIMARY KEY,
    USER_PW     VARCHAR2(100) NOT NULL,
    USER_NICK   VARCHAR2(100) NOT NULL,
    CRYSTAL     NUMBER        DEFAULT 0,
    TEAM_NAME   VARCHAR2(100)
);

-- 2. 선수 마스터
CREATE TABLE TBL_PLAYERS (
    PLAYER_SEQ      NUMBER        CONSTRAINT PK_PLAYERS PRIMARY KEY,
    PLAYER_NAME     VARCHAR2(100) NOT NULL,
    RACE            CHAR(1)       NOT NULL CHECK (RACE IN ('T', 'P', 'Z')),
    RARITY          VARCHAR2(10)  NOT NULL CHECK (RARITY IN ('N', 'R', 'SR', 'SSR', 'UR')),
    STAT_ATTACK     NUMBER(3)     DEFAULT 50,
    STAT_DEFENSE    NUMBER(3)     DEFAULT 50,
    STAT_MACRO      NUMBER(3)     DEFAULT 50,
    STAT_MICRO      NUMBER(3)     DEFAULT 50,
    STAT_LUCK       NUMBER(3)     DEFAULT 50,
    PLAYER_IMG_URL  VARCHAR2(255),
    PLAYER_COST     NUMBER(3)     DEFAULT 10
);

-- 3. 시즌 팩
CREATE TABLE TBL_PACKS (
    PACK_SEQ        NUMBER        CONSTRAINT PK_PACKS PRIMARY KEY,
    PACK_NAME       VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(500),
    COST_CRYSTAL    NUMBER        DEFAULT 0,
    BANNER_IMG_URL  VARCHAR2(255),
    IS_AVAILABLE    CHAR(1)       DEFAULT 'Y' CHECK (IS_AVAILABLE IN ('Y', 'N'))
);

-- 4. 팩 구성 선수 (확률표)
CREATE TABLE TBL_PACK_CONTENTS (
    PACK_CONTENT_SEQ NUMBER       CONSTRAINT PK_PACK_CONTENTS PRIMARY KEY,
    PACK_SEQ         NUMBER       NOT NULL CONSTRAINT FK_PACK_CONTENTS_PACK   REFERENCES TBL_PACKS(PACK_SEQ),
    PLAYER_SEQ       NUMBER       NOT NULL CONSTRAINT FK_PACK_CONTENTS_PLAYER REFERENCES TBL_PLAYERS(PLAYER_SEQ),
    DRAW_PROBABILITY NUMBER(7, 6) NOT NULL CHECK (DRAW_PROBABILITY > 0 AND DRAW_PROBABILITY <= 1),
    CONSTRAINT UK_PACK_PLAYER UNIQUE (PACK_SEQ, PLAYER_SEQ)
);

-- 5. 유저 보유 선수
CREATE TABLE TBL_OWNED_PLAYERS (
    OWNED_PLAYER_SEQ       NUMBER       CONSTRAINT PK_OWNED_PLAYERS PRIMARY KEY,
    USER_ID                VARCHAR2(50) NOT NULL CONSTRAINT FK_OWNED_PLAYER_USER   REFERENCES TBL_USERS(USER_ID),
    PLAYER_SEQ             NUMBER       NOT NULL CONSTRAINT FK_OWNED_PLAYER_MASTER REFERENCES TBL_PLAYERS(PLAYER_SEQ),
    CURRENT_ATTACK         NUMBER(3)    DEFAULT NULL,
    CURRENT_DEFENSE        NUMBER(3)    DEFAULT NULL,
    CURRENT_MACRO          NUMBER(3)    DEFAULT NULL,
    CURRENT_MICRO          NUMBER(3)    DEFAULT NULL,
    CURRENT_LUCK           NUMBER(3)    DEFAULT NULL,
    ACQUIRED_AT            DATE         DEFAULT SYSDATE,
    CURRENT_RARITY         VARCHAR2(10) NOT NULL,
    ACQUIRED_FROM_PACK_SEQ NUMBER       CONSTRAINT FK_OWNED_PLAYER_PACK REFERENCES TBL_PACKS(PACK_SEQ)
);

-- 6. 경기 기록
CREATE TABLE TBL_MATCH_RECORDS (
    MATCH_SEQ        NUMBER       CONSTRAINT PK_MATCH_RECORDS PRIMARY KEY,
    OWNED_PLAYER_SEQ NUMBER       NOT NULL CONSTRAINT FK_MATCH_RECORDS_OWNED REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    MATCH_TYPE       VARCHAR2(20) DEFAULT 'PVE',
    OPPONENT_NAME    VARCHAR2(100),
    OPPONENT_RACE    VARCHAR2(10),
    MAP_NAME         VARCHAR2(100),
    IS_WIN           CHAR(1)      NOT NULL CHECK (IS_WIN IN ('Y', 'N')),
    MATCH_DATE       DATE         DEFAULT SYSDATE
);

-- 7. PVE 엔트리 (1군)
CREATE TABLE TBL_PVE_ENTRY (
    PVE_ENTRY_SEQ    NUMBER       CONSTRAINT PK_PVE_ENTRY PRIMARY KEY,
    USER_ID          VARCHAR2(50) NOT NULL CONSTRAINT FK_PVE_ENTRY_USER         REFERENCES TBL_USERS(USER_ID),
    OWNED_PLAYER_SEQ NUMBER       NOT NULL CONSTRAINT FK_PVE_ENTRY_OWNED_PLAYER REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ),
    SLOT_NUMBER      NUMBER(1)    NOT NULL CHECK (SLOT_NUMBER BETWEEN 1 AND 7),
    CONSTRAINT UK_USER_SLOT         UNIQUE (USER_ID, SLOT_NUMBER),
    CONSTRAINT UK_USER_OWNED_PLAYER UNIQUE (USER_ID, OWNED_PLAYER_SEQ)
);

-- 8. PVE 메인 진행
CREATE TABLE USER_PVE_PROGRESS (
    USER_ID      VARCHAR2(50) NOT NULL,
    STAGE_LEVEL  NUMBER       NOT NULL,
    STAGE_STATUS VARCHAR2(20) NOT NULL,
    UPDATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PVE_PROGRESS     PRIMARY KEY (USER_ID, STAGE_LEVEL),
    CONSTRAINT FK_USER_PVE_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_USER_PVE_STATUS       CHECK (STAGE_STATUS IN ('CLEARED', 'IN_PROGRESS', 'LOCKED'))
);

-- 9. PVE 서브스테이지 마스터
CREATE TABLE TBL_PVE_SUBSTAGES (
    STAGE_LEVEL        NUMBER        NOT NULL,
    SUB_LEVEL          NUMBER        NOT NULL,
    SUB_TITLE          VARCHAR2(100) NOT NULL,
    OPPONENT_TEAM_NAME VARCHAR2(100),
    CONSTRAINT PK_PVE_SUBSTAGES PRIMARY KEY (STAGE_LEVEL, SUB_LEVEL)
);

-- 10. 사용자 서브스테이지 진행
CREATE TABLE USER_PVE_SUBSTAGE_PROGRESS (
    USER_ID     VARCHAR2(50) NOT NULL,
    STAGE_LEVEL NUMBER       NOT NULL,
    SUB_LEVEL   NUMBER       NOT NULL,
    IS_CLEARED  CHAR(1)      DEFAULT 'Y' NOT NULL CHECK (IS_CLEARED = 'Y'),
    CLEARED_AT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PVE_SUBSTAGE       PRIMARY KEY (USER_ID, STAGE_LEVEL, SUB_LEVEL),
    CONSTRAINT FK_USER_PVE_SUBSTAGE_USER   FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_PVE_SUBSTAGE_MASTER FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE
);
CREATE INDEX IDX_USER_PVE_SUBSTAGE_USER ON USER_PVE_SUBSTAGE_PROGRESS (USER_ID, STAGE_LEVEL);

-- 11. 맵 마스터
CREATE TABLE TBL_MAPS (
    MAP_ID      VARCHAR2(50)   CONSTRAINT PK_MAPS PRIMARY KEY,
    MAP_NAME    VARCHAR2(100)  NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    WIN_RATE_T  NUMBER(5, 2)   DEFAULT 50.00,
    WIN_RATE_P  NUMBER(5, 2)   DEFAULT 50.00,
    WIN_RATE_Z  NUMBER(5, 2)   DEFAULT 50.00
);

-- 12. PVE 서브스테이지별 맵
CREATE TABLE TBL_PVE_SUBSTAGE_MAPS (
    STAGE_LEVEL NUMBER       NOT NULL,
    SUB_LEVEL   NUMBER       NOT NULL,
    SET_NUMBER  NUMBER(1)    NOT NULL,
    MAP_ID      VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PVE_SUBSTAGE_MAPS    PRIMARY KEY (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER),
    CONSTRAINT FK_SUBSTAGE_MAPS_MASTER FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE,
    CONSTRAINT FK_SUBSTAGE_MAPS_MAP    FOREIGN KEY (MAP_ID) REFERENCES TBL_MAPS(MAP_ID)
);

-- 13. PVE AI 엔트리
-- ★ BUILD_ID FK는 TBL_BUILDS 생성 이후 ALTER TABLE로 추가 (순서 의존성 문제 해결)
CREATE TABLE TBL_PVE_OPPONENTS (
    OPPONENT_ID NUMBER    CONSTRAINT PK_PVE_OPPONENTS PRIMARY KEY,
    STAGE_LEVEL NUMBER    NOT NULL,
    SUB_LEVEL   NUMBER    NOT NULL,
    PLAYER_SEQ  NUMBER    NOT NULL,
    SET_NUMBER  NUMBER(1) NULL,
    BUILD_ID    NUMBER    NULL,
    CONSTRAINT FK_PVE_OPPONENTS_SUBSTAGE FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE,
    CONSTRAINT FK_PVE_OPPONENTS_PLAYER   FOREIGN KEY (PLAYER_SEQ) REFERENCES TBL_PLAYERS(PLAYER_SEQ)
);

-- =====================================================================
-- ★ 14. 빌드 마스터 (수정된 핵심 테이블)
--    구버전(new2.sql)에는 USER_ID / PLAY_STYLE / EXPAND_STYLE / AGGRESSION / TECH_STYLE 없음
--    → 이 컬럼들이 없어서 insertBuild 시 ORA-00904 오류 발생
-- =====================================================================
--     PLAY_STYLE  : HARASS_FOCUS=견제 / DEFENSIVE=방어 / AGGRESSIVE=공격
--     EXPAND_STYLE: FAST_MULTI=패스트 / NORMAL_MULTI=일반 / LATE_MULTI=늦은
--     AGGRESSION  : MIN_MULTI=최소 / MID_MULTI=중간 / MAX_MULTI=최대
--     TECH_STYLE  : FAST_TECH=빠른(5분) / MID_TECH=중간(7분) / LATE_TECH=느린(10분)
CREATE TABLE TBL_BUILDS (
    BUILD_ID     NUMBER        CONSTRAINT PK_BUILDS PRIMARY KEY,
    USER_ID      VARCHAR2(50)  CONSTRAINT FK_BUILDS_USER REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    BUILD_NAME   VARCHAR2(100) NOT NULL,
    RACE         CHAR(1)       NOT NULL CHECK (RACE IN ('T', 'P', 'Z')),
    VS_RACE      CHAR(1)       NOT NULL CHECK (VS_RACE IN ('T', 'P', 'Z', 'A')),
    PLAY_STYLE   VARCHAR2(15)  DEFAULT 'AGGRESSIVE' NOT NULL
                               CONSTRAINT CHK_BUILDS_PLAY_STYLE
                               CHECK (PLAY_STYLE IN ('HARASS_FOCUS', 'DEFENSIVE', 'AGGRESSIVE')),
    EXPAND_STYLE VARCHAR2(15)  DEFAULT 'NORMAL_MULTI' NOT NULL
                               CONSTRAINT CHK_BUILDS_EXPAND_STYLE
                               CHECK (EXPAND_STYLE IN ('FAST_MULTI', 'NORMAL_MULTI', 'LATE_MULTI')),
    AGGRESSION   VARCHAR2(15)  DEFAULT 'MID_MULTI' NOT NULL
                               CONSTRAINT CHK_BUILDS_AGGRESSION
                               CHECK (AGGRESSION IN ('MIN_MULTI', 'MID_MULTI', 'MAX_MULTI')),
    TECH_STYLE   VARCHAR2(15)  DEFAULT 'MID_TECH' NOT NULL
                               CONSTRAINT CHK_BUILDS_TECH_STYLE
                               CHECK (TECH_STYLE IN ('FAST_TECH', 'MID_TECH', 'LATE_TECH')),
    MAX_TIER     NUMBER(1)     DEFAULT 3 NOT NULL
                               CONSTRAINT CHK_BUILDS_MAX_TIER
                               CHECK (MAX_TIER IN (1, 2, 3)),
    SCRIPT_CONTENT CLOB,
    CREATED_AT   DATE          DEFAULT SYSDATE,
    CONSTRAINT UK_USER_BUILD_NAME_RACE UNIQUE (USER_ID, BUILD_NAME, RACE, VS_RACE)
);
COMMENT ON COLUMN TBL_BUILDS.PLAY_STYLE   IS '플레이스타일: HARASS_FOCUS=견제 / DEFENSIVE=방어 / AGGRESSIVE=공격';
COMMENT ON COLUMN TBL_BUILDS.EXPAND_STYLE IS '첫멀티타이밍: FAST_MULTI=패스트(즉시) / NORMAL_MULTI=일반(5분) / LATE_MULTI=늦은(10분)';
COMMENT ON COLUMN TBL_BUILDS.AGGRESSION   IS '확장성향: MIN_MULTI=최소 / MID_MULTI=중간 / MAX_MULTI=최대';
COMMENT ON COLUMN TBL_BUILDS.TECH_STYLE   IS '테크성향: FAST_TECH=빠른(5분) / MID_TECH=일반(10분) / LATE_TECH=느린(15분)';
COMMENT ON COLUMN TBL_BUILDS.MAX_TIER     IS '최대 티어: 1=1티어만 / 2=1~2티어 / 3=전체(기본)';

-- ★ TBL_BUILDS 생성 후 TBL_PVE_OPPONENTS의 BUILD_ID FK 추가
ALTER TABLE TBL_PVE_OPPONENTS
ADD CONSTRAINT FK_PVE_OPP_BUILD FOREIGN KEY (BUILD_ID) REFERENCES TBL_BUILDS(BUILD_ID);

-- 15. 페이즈별 유닛 구성
CREATE TABLE TBL_BUILD_UNITS (
    BUILD_UNIT_ID NUMBER       CONSTRAINT PK_BUILD_UNITS PRIMARY KEY,
    BUILD_ID      NUMBER       NOT NULL CONSTRAINT FK_BU_BUILD REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    PHASE         VARCHAR2(10) NOT NULL CHECK (PHASE IN ('EARLY', 'MID', 'LATE')),
    UNIT_ID       VARCHAR2(50) NOT NULL,
    PRIORITY      NUMBER(1)    DEFAULT 1 NOT NULL CHECK (PRIORITY BETWEEN 1 AND 5),
    CONSTRAINT UK_BUILD_PHASE_UNIT UNIQUE (BUILD_ID, PHASE, UNIT_ID)
);
COMMENT ON COLUMN TBL_BUILD_UNITS.PRIORITY IS '1=최우선(가장많이생산) ~ 5=보조';

-- 16. 선수-빌드 연결
CREATE TABLE TBL_OWNED_BUILDS (
    OWNED_BUILD_SEQ NUMBER NOT NULL CONSTRAINT PK_OWNED_BUILDS PRIMARY KEY,
    PLAYER_SEQ      NUMBER NOT NULL CONSTRAINT FK_OB_PLAYER REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    BUILD_ID        NUMBER NOT NULL CONSTRAINT FK_OB_BUILD  REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    CONSTRAINT UK_PLAYER_BUILD UNIQUE (PLAYER_SEQ, BUILD_ID)
);
COMMENT ON TABLE TBL_OWNED_BUILDS IS '보유선수(OWNED_PLAYER)가 사용하는 빌드 연결';

-- 17. PVE 배틀 세션
CREATE TABLE TBL_PVE_BATTLE_SESSION (
    BATTLE_ID       NUMBER        CONSTRAINT PK_PVE_BATTLE_SESSION PRIMARY KEY,
    USER_ID         VARCHAR2(50)  NOT NULL,
    STAGE_LEVEL     NUMBER        NOT NULL,
    SUB_LEVEL       NUMBER        NOT NULL,
    MATCHUP_DATA    CLOB,
    MY_TEAM_DATA    CLOB,
    AI_TEAM_DATA    CLOB,
    GAME_STATE_DATA CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSDATE,
    STATUS          VARCHAR2(20)  DEFAULT 'IN_PROGRESS' CHECK (STATUS IN ('IN_PROGRESS', 'COMPLETED')),
    MY_WINS         NUMBER        DEFAULT 0,
    AI_WINS         NUMBER        DEFAULT 0,
    CURRENT_SET     NUMBER        DEFAULT 1,
    CONSTRAINT UK_PVE_ACTIVE_BATTLE UNIQUE (USER_ID, STAGE_LEVEL, SUB_LEVEL, STATUS)
);


-- =====================================================================
-- 4. 트리거 생성
-- =====================================================================

CREATE OR REPLACE TRIGGER TRG_PVE_BATTLE_SESSION_PK
BEFORE INSERT ON TBL_PVE_BATTLE_SESSION FOR EACH ROW
WHEN (NEW.BATTLE_ID IS NULL)
BEGIN SELECT SEQ_PVE_BATTLE_SESSION.NEXTVAL INTO :NEW.BATTLE_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_BUILDS_PK
BEFORE INSERT ON TBL_BUILDS FOR EACH ROW
WHEN (NEW.BUILD_ID IS NULL)
BEGIN SELECT SEQ_BUILDS.NEXTVAL INTO :NEW.BUILD_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_BUILD_UNITS_PK
BEFORE INSERT ON TBL_BUILD_UNITS FOR EACH ROW
WHEN (NEW.BUILD_UNIT_ID IS NULL)
BEGIN SELECT SEQ_BUILD_UNITS.NEXTVAL INTO :NEW.BUILD_UNIT_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_OWNED_BUILDS_PK
BEFORE INSERT ON TBL_OWNED_BUILDS FOR EACH ROW
WHEN (NEW.OWNED_BUILD_SEQ IS NULL)
BEGIN SELECT SEQ_OWNED_BUILDS.NEXTVAL INTO :NEW.OWNED_BUILD_SEQ FROM DUAL; END;
/


-- =====================================================================
-- 5. 마스터 데이터 삽입
-- =====================================================================

-- 1. 사용자 (10명)
-- 테스트 유저 중복 방지
DELETE FROM TBL_USERS WHERE USER_ID IN ('testuser1','testuser2','testuser3','testuser4','testuser5',
                                         'testuser6','testuser7','testuser8','testuser9','testuser10');
COMMIT;

INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser1',  '1234', '테스터1',  1000, 'TestUser1');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser2',  '1234', '테스터2',  1000, 'TestUser2');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser3',  '1234', '테스터3',  1000, 'TestUser3');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser4',  '1234', '테스터4',  1000, 'TestUser4');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser5',  '1234', '테스터5',  1000, 'TestUser5');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser6',  '1234', '테스터6',  1000, 'TestUser6');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser7',  '1234', '테스터7',  1000, 'TestUser7');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser8',  '1234', '테스터8',  1000, 'TestUser8');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser9',  '1234', '테스터9',  1000, 'TestUser9');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser10', '1234', '테스터10', 1000, 'TestUser10');

-- 2. 선수 마스터 (22명)
-- SR 등급
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '금선2',    'T', 'SR',  17, 64, 25, 15, 13, '/image/players/geumseon2.png',   5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '요닝',     'Z', 'SR',  13, 31, 13, 16, 61, '/image/players/yoning.png',       5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '슬아',     'Z', 'SR',  35, 22, 11, 27, 45, '/image/players/sulah.png',        5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '빵리나',   'P', 'SR',  25, 42, 25, 21, 24, '/image/players/bbangrina.png',    5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '카히리',   'Z', 'SR',  15, 21, 31, 50, 17, '/image/players/kahiri.png',       5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '지두두',   'T', 'SR',  40, 31, 39, 15, 12, '/image/players/jidudu.png',       5);
-- UR 등급
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '서지수',   'T', 'UR',  38, 44, 40, 33, 35, '/image/players/seojisu.png',      10);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '보혜',     'P', 'UR',  40, 35, 40, 30, 40, '/image/players/bohye.png',        10);
-- SSR 등급
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '다린',     'T', 'SSR', 32, 30, 32, 30, 32, '/image/players/darin.png',        7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '애공',     'P', 'SSR', 32, 30, 32, 30, 32, '/image/players/aegong.png',       7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '혜로로',   'Z', 'SSR', 32, 30, 32, 30, 32, '/image/players/hyeroro.png',      7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '우힝이',   'T', 'SSR', 32, 30, 32, 30, 32, '/image/players/woohinge.png',     7);
-- R 등급
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '꼬니부깅', 'P', 'R',   22, 22, 22, 22, 22, '/image/players/ggonibuking.png',  3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '묘아',     'P', 'R',   22, 22, 22, 22, 22, '/image/players/myoah.png',        3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '아라미',   'Z', 'R',   22, 22, 22, 22, 22, '/image/players/ahrami.png',       3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '뽀누나',   'T', 'R',   22, 22, 22, 22, 22, '/image/players/bbonuna.png',      3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '하두링',   'P', 'R',   22, 22, 22, 22, 22, '/image/players/haduring.png',     3);
-- N 등급
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '모리',     'T', 'N',   20, 20, 20, 20, 10, '/image/players/mori.png',         1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '2라니',    'Z', 'N',   20, 20, 20, 20, 10, '/image/players/2rani.png',        1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '선정은',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/sunjungeun.png',   1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '비타밍',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/vitaming.png',     1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_MACRO, STAT_MICRO, STAT_LUCK, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '정다닝',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/jungdaning.png',   1);

-- 3. 팩 마스터 (2개)
INSERT INTO TBL_PACKS (PACK_SEQ, PACK_NAME, DESCRIPTION, COST_CRYSTAL, BANNER_IMG_URL, IS_AVAILABLE) VALUES (SEQ_PACKS.NEXTVAL, '마이 여캠 스타리그 출시팩 1', '마이 여캠 스타리그 출시 기념 첫번째 팩입니다!', 100, '/image/mystarleague_1pack.png', 'Y');
INSERT INTO TBL_PACKS (PACK_SEQ, PACK_NAME, DESCRIPTION, COST_CRYSTAL, BANNER_IMG_URL, IS_AVAILABLE) VALUES (SEQ_PACKS.NEXTVAL, '마이 여캠 스타리그 출시팩 2', '마이 여캠 스타리그 출시 기념 두 번째 팩입니다',  100, '/image/mystarleague_2pack.png', 'Y');

-- 4. 팩 구성품 (팩1: PACK_SEQ=1) 확률 합계 = 1.000000
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  7, 0.010000); -- UR  서지수  1%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  9, 0.015000); -- SSR 다린   1.5%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 10, 0.015000); -- SSR 애공   1.5%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  1, 0.016666); -- SR  금선2
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  2, 0.016666); -- SR  요닝
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  3, 0.016668); -- SR  슬아
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 13, 0.060000); -- R   꼬니부깅 6%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 14, 0.060000); -- R   묘아
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 15, 0.060000); -- R   아라미
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 16, 0.060000); -- R   뽀누나
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 17, 0.060000); -- R   하두링
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 18, 0.122000); -- N   모리  12.2%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 19, 0.122000); -- N   2라니
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 20, 0.122000); -- N   선정은
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 21, 0.122000); -- N   비타밍
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 22, 0.122000); -- N   정다닝

-- 팩 구성품 (팩2: PACK_SEQ=2) 확률 합계 = 1.000000
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  8, 0.010000); -- UR  보혜   1%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 11, 0.015000); -- SSR 혜로로 1.5%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 12, 0.015000); -- SSR 우힝이 1.5%
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  4, 0.016666); -- SR  빵리나
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  5, 0.016666); -- SR  카히리
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  6, 0.016668); -- SR  지두두
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 13, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 14, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 15, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 16, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 17, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 18, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 19, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 20, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 21, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 22, 0.122000);

-- 5. PVE 서브스테이지
INSERT INTO TBL_PVE_SUBSTAGES (STAGE_LEVEL, SUB_LEVEL, SUB_TITLE, OPPONENT_TEAM_NAME)
VALUES (1, 1, '오프닝 매치 : 빛의 개막전', '프로리그 등록 예선 첫 경기.');

-- 6. 맵 마스터
INSERT INTO TBL_MAPS (MAP_ID, MAP_NAME, DESCRIPTION, WIN_RATE_T, WIN_RATE_P, WIN_RATE_Z)
VALUES ('fighting_spirit', 'Fighting Spirit', '2인용 맵. 전략적인 초반 빌드와 컨트롤이 승패를 가릅니다.', 50.00, 50.00, 50.00);

-- 7. PVE 맵 구성 (5세트)
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 1, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 2, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 3, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 4, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 5, 'fighting_spirit');

-- 8. PVE AI 엔트리 (5명)
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 18, 1);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 19, 2);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 14, 3);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1,  5, 4);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 22, 5);

COMMIT;





-- TBL_BUILDS 컬럼 추가
ALTER TABLE TBL_BUILDS ADD PREFERRED_BUILDINGS VARCHAR2(500);
ALTER TABLE TBL_BUILDS ADD BUILD_PRESET        VARCHAR2(100);
 
-- 기존 컬럼 제거 (선택사항 — 데이터 보존이 필요하면 주석 처리)
ALTER TABLE TBL_BUILDS DROP COLUMN TECH_STYLE;
ALTER TABLE TBL_BUILDS DROP COLUMN EXPAND_STYLE;
 
COMMIT;


ALTER TABLE TBL_BUILDS ADD WIN_COUNT  NUMBER DEFAULT 0;
ALTER TABLE TBL_BUILDS ADD LOSE_COUNT NUMBER DEFAULT 0;
COMMIT;

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_BUILDS' ORDER BY COLUMN_ID;



UPDATE TBL_USERS
SET TRAIN_POINT = TRAIN_POINT + 10
WHERE USER_ID = 'testuser3';



-- ========================================================
-- 컨디션 & 경기력(연승) 시스템 마이그레이션
-- ========================================================
 
-- 1. TBL_OWNED_PLAYERS에 컬럼 추가
ALTER TABLE TBL_OWNED_PLAYERS
    ADD CONDITION VARCHAR2(10) DEFAULT 'NORMAL'
        CHECK (CONDITION IN ('PEAK','GOOD','NORMAL','TIRED','WORST'));
 
ALTER TABLE TBL_OWNED_PLAYERS
    ADD WIN_STREAK NUMBER(3) DEFAULT 0;
 
-- 2. 기존 선수 데이터 초기화 (컨디션: NORMAL, 연승: 0)
UPDATE TBL_OWNED_PLAYERS SET CONDITION = 'NORMAL', WIN_STREAK = 0;
COMMIT;











-- ★ 강화 시스템: TBL_OWNED_PLAYERS에 강화 컬럼 추가
-- 강화 스탯은 경기 패배로 절대 내려가지 않는 별도 스탯

ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_LEVEL   NUMBER(2) DEFAULT 0;
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_ATTACK  NUMBER    DEFAULT 0;
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_DEFENSE NUMBER    DEFAULT 0;
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_MACRO   NUMBER    DEFAULT 0;
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_MICRO   NUMBER    DEFAULT 0;
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_LUCK    NUMBER    DEFAULT 0;

-- 기존 선수 데이터 초기화
UPDATE TBL_OWNED_PLAYERS SET
    ENHANCE_LEVEL   = 0,
    ENHANCE_ATTACK  = 0,
    ENHANCE_DEFENSE = 0,
    ENHANCE_MACRO   = 0,
    ENHANCE_MICRO   = 0,
    ENHANCE_LUCK    = 0;

COMMIT;







-- TBL_PVE_BATTLE_SESSION에 SET_RESULTS_DATA 컬럼 추가
-- 세션 만료 후 재접속해도 세트별 선수 추적 정보를 복구하기 위한 컬럼

ALTER TABLE TBL_PVE_BATTLE_SESSION
    ADD SET_RESULTS_DATA CLOB;

-- 적용 확인
-- SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS
-- WHERE TABLE_NAME = 'TBL_PVE_BATTLE_SESSION';




-- 기존 FK 제거 후 CASCADE 옵션으로 재생성
ALTER TABLE TBL_PVE_ENTRY 
    DROP CONSTRAINT FK_PVE_ENTRY_OWNED_PLAYER;

ALTER TABLE TBL_PVE_ENTRY 
    ADD CONSTRAINT FK_PVE_ENTRY_OWNED_PLAYER 
    FOREIGN KEY (OWNED_PLAYER_SEQ) 
    REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) 
    ON DELETE CASCADE;
 
 
 commit;
 
 
 
ALTER TABLE TBL_OWNED_PLAYERS ADD ENHANCE_STREAK NUMBER DEFAULT 0;
UPDATE TBL_OWNED_PLAYERS SET ENHANCE_STREAK = 0;
COMMIT;






















-- ============================================================
-- 마이그레이션: 견제 성향(HARASS_STYLE) 컬럼 추가
-- 대상 테이블: TBL_BUILDS
-- 실행 순서: 1) 컬럼 추가 → 2) 기존 데이터 기본값 채우기 → 3) CHECK 제약 추가
-- ============================================================

-- 1. HARASS_STYLE 컬럼 추가 (기본값 NORMAL_HARASS)
ALTER TABLE TBL_BUILDS ADD (
    HARASS_STYLE VARCHAR2(20) DEFAULT 'NORMAL_HARASS'
);

-- 2. 기존 row 전부 기본값으로 채우기 (NULL 방지)
UPDATE TBL_BUILDS
SET HARASS_STYLE = 'NORMAL_HARASS'
WHERE HARASS_STYLE IS NULL;

-- 3. CHECK 제약 추가 (허용 값 3종)
ALTER TABLE TBL_BUILDS ADD CONSTRAINT CK_BUILDS_HARASS_STYLE
    CHECK (HARASS_STYLE IN ('NO_HARASS', 'NORMAL_HARASS', 'HEAVY_HARASS'));

-- 4. 컬럼 설명
COMMENT ON COLUMN TBL_BUILDS.HARASS_STYLE IS
    '견제 성향: NO_HARASS(견제없음) / NORMAL_HARASS(일반견제, 2~6회) / HEAVY_HARASS(강한견제, 7~11회)';

COMMIT;

-- ============================================================
-- (선택) 기존 PLAY_STYLE 값 마이그레이션
-- 구버전 HARASS_FOCUS 빌드 → 일반 스타일로 전환하고 강한 견제로 분류
-- ============================================================
UPDATE TBL_BUILDS
SET    PLAY_STYLE   = 'NORMAL',
       HARASS_STYLE = 'HEAVY_HARASS'
WHERE  PLAY_STYLE = 'HARASS_FOCUS';

COMMIT;











-- =====================================================================
-- 일일 미션 시스템 테이블 생성
-- =====================================================================

-- 기존 테이블 삭제 (있다면)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_USER_DAILY_MISSIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_DAILY_MISSIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DAILY_MISSIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 시퀀스 생성
CREATE SEQUENCE SEQ_DAILY_MISSIONS START WITH 1 INCREMENT BY 1 NOCACHE;

-- 1. 일일 미션 마스터 테이블 (미션 정의)
CREATE TABLE TBL_DAILY_MISSIONS (
    MISSION_ID          NUMBER CONSTRAINT PK_DAILY_MISSIONS PRIMARY KEY,
    MISSION_TYPE        VARCHAR2(50) NOT NULL,  -- 'PVE_WIN', 'PVE_PLAY', 'GACHA', 'ENHANCE', 'LOGIN'
    MISSION_TITLE       VARCHAR2(200) NOT NULL,
    MISSION_DESC        VARCHAR2(500),
    TARGET_COUNT        NUMBER DEFAULT 1,       -- 목표 달성 횟수
    REWARD_CRYSTAL      NUMBER DEFAULT 0,       -- 보상 크리스탈
    REWARD_EXP          NUMBER DEFAULT 0,       -- 보상 경험치 (향후 레벨 시스템용)
    MISSION_ICON        VARCHAR2(50),           -- 아이콘 이모지
    DISPLAY_ORDER       NUMBER DEFAULT 0,       -- 표시 순서
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT          DATE DEFAULT SYSDATE
);

-- 2. 유저별 일일 미션 진행 상황 테이블
CREATE TABLE TBL_USER_DAILY_MISSIONS (
    USER_ID             VARCHAR2(50) NOT NULL,
    MISSION_ID          NUMBER NOT NULL,
    CURRENT_COUNT       NUMBER DEFAULT 0,       -- 현재 진행 횟수
    IS_COMPLETED        CHAR(1) DEFAULT 'N' CHECK (IS_COMPLETED IN ('Y', 'N')),
    IS_CLAIMED          CHAR(1) DEFAULT 'N' CHECK (IS_CLAIMED IN ('Y', 'N')),
    COMPLETED_AT        DATE,
    CLAIMED_AT          DATE,
    RESET_DATE          DATE DEFAULT TRUNC(SYSDATE), -- 마지막 리셋 날짜
    CONSTRAINT PK_USER_DAILY_MISSIONS PRIMARY KEY (USER_ID, MISSION_ID),
    CONSTRAINT FK_USER_DAILY_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_DAILY_MISSION FOREIGN KEY (MISSION_ID) REFERENCES TBL_DAILY_MISSIONS(MISSION_ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IDX_USER_DAILY_RESET ON TBL_USER_DAILY_MISSIONS(USER_ID, RESET_DATE);
CREATE INDEX IDX_DAILY_MISSION_TYPE ON TBL_DAILY_MISSIONS(MISSION_TYPE);

-- =====================================================================
-- 기본 일일 미션 데이터 삽입
-- =====================================================================

-- 미션 1: PVE 1회 승리
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, 
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'PVE_WIN', '첫 승리', 'PVE 전투에서 1회 승리하기',
    1, 50, 100, '🏆', 1
);

-- 미션 2: PVE 3회 플레이
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC,
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'PVE_PLAY', '적극적인 도전', 'PVE 전투 3회 플레이 (승패 무관)',
    3, 100, 150, '⚔️', 2
);

-- 미션 3: PVE 5회 승리
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC,
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'PVE_WIN', '연승 행진', 'PVE 전투에서 5회 승리하기',
    5, 200, 300, '🔥', 3
);

-- 미션 4: 가챠 1회 진행
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC,
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'GACHA', '스카우팅', '선수 영입 1회 진행하기 (1회/10회 모두 가능)',
    1, 30, 50, '🌟', 4
);

-- 미션 5: 선수 강화 2회
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC,
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'ENHANCE', '선수 육성', '선수를 2회 강화하기',
    2, 50, 80, '⚡', 5
);

-- 미션 6: 로그인
INSERT INTO TBL_DAILY_MISSIONS (
    MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC,
    TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER
) VALUES (
    SEQ_DAILY_MISSIONS.NEXTVAL, 'LOGIN', '출석 체크', '오늘 접속하기',
    1, 20, 50, '📅', 6
);

COMMIT;

-- =====================================================================
-- 미션 진행 상황 초기화 프로시저 (매일 자동 실행용)
-- =====================================================================
CREATE OR REPLACE PROCEDURE RESET_DAILY_MISSIONS AS
BEGIN
    -- 어제 날짜의 미션 데이터 삭제
    DELETE FROM TBL_USER_DAILY_MISSIONS 
    WHERE RESET_DATE < TRUNC(SYSDATE);
    
    COMMIT;
END;
/


-- ============================================
-- 일일 미션 내용 변경 SQL
-- ============================================

-- 1. "첫 승리" → "라운드 클리어" (1회)
UPDATE TBL_DAILY_MISSIONS
SET MISSION_TITLE = '라운드 클리어',
    MISSION_DESC = 'PVE 라운드 1회 클리어하기',
    TARGET_COUNT = 1
WHERE MISSION_TYPE = 'PVE_WIN';

-- 2. "적극적인 도전" (3회 플레이) → "완벽한 승리" (3승0패)
UPDATE TBL_DAILY_MISSIONS
SET MISSION_TITLE = '완벽한 승리',
    MISSION_DESC = '3승0패로 라운드 클리어하기',
    TARGET_COUNT = 3,
    MISSION_TYPE = 'PVE_PERFECT'  -- 새로운 미션 타입
WHERE MISSION_TYPE = 'PVE_PLAY';

-- 3. "연승 행진" (5회 승리) → "선수 훈련" (1회)
UPDATE TBL_DAILY_MISSIONS
SET MISSION_TITLE = '선수 훈련',
    MISSION_DESC = '선수 훈련 1회 진행하기',
    TARGET_COUNT = 1,
    MISSION_ICON = '💪',
    MISSION_TYPE = 'TRAIN'  -- 새로운 미션 타입
WHERE MISSION_ID = 3;

-- 4. "선수 육성" (2회 강화) → (1회 강화)
UPDATE TBL_DAILY_MISSIONS
SET MISSION_TITLE = '선수 육성',
    MISSION_DESC = '선수 1회 강화하기',
    TARGET_COUNT = 1
WHERE MISSION_TYPE = 'ENHANCE';

COMMIT;






-- ============================================================
-- TBL_BUILDS 변경사항
-- 1. MAX_BASES 컬럼 추가 (유저가 직접 설정하는 최대 기지 수)
-- 2. AGGRESSION CHECK 제약조건 수정
--    MIN_MULTI / MID_MULTI / MAX_MULTI
--    → FAST_MULTI / NORMAL_MULTI / SLOW_MULTI (멀티 타이밍 제어)
-- 3. AGGRESSION 기본값 및 COMMENT 수정
-- ============================================================

-- 1. MAX_BASES 컬럼 추가
ALTER TABLE TBL_BUILDS
ADD MAX_BASES NUMBER(2) DEFAULT 4 NOT NULL;

COMMENT ON COLUMN TBL_BUILDS.MAX_BASES
    IS '최대 기지 수 (본진 포함, 기본값 4 / 저그는 해처리+레어+하이브 합산)';

-- 2. AGGRESSION CHECK 제약조건 삭제 후 재생성
ALTER TABLE TBL_BUILDS
DROP CONSTRAINT CHK_BUILDS_AGGRESSION;

ALTER TABLE TBL_BUILDS
MODIFY AGGRESSION VARCHAR2(15) DEFAULT 'NORMAL_MULTI' NOT NULL;

ALTER TABLE TBL_BUILDS
ADD CONSTRAINT CHK_BUILDS_AGGRESSION
    CHECK (AGGRESSION IN ('FAST_MULTI', 'NORMAL_MULTI', 'SLOW_MULTI'));

COMMENT ON COLUMN TBL_BUILDS.AGGRESSION
    IS '멀티 타이밍: FAST_MULTI=빠른멀티 / NORMAL_MULTI=일반멀티 / SLOW_MULTI=느린멀티';

-- 3. 기존 데이터 마이그레이션 (구버전 값 → 신버전 값)
UPDATE TBL_BUILDS SET AGGRESSION = 'SLOW_MULTI'   WHERE AGGRESSION = 'MIN_MULTI';
UPDATE TBL_BUILDS SET AGGRESSION = 'NORMAL_MULTI' WHERE AGGRESSION = 'MID_MULTI';
UPDATE TBL_BUILDS SET AGGRESSION = 'FAST_MULTI'   WHERE AGGRESSION = 'MAX_MULTI';
COMMIT;

-- 4. PLAY_STYLE CHECK 제약조건도 수정 (구버전 HARASS_FOCUS 제거)
ALTER TABLE TBL_BUILDS
DROP CONSTRAINT CHK_BUILDS_PLAY_STYLE;

ALTER TABLE TBL_BUILDS
ADD CONSTRAINT CHK_BUILDS_PLAY_STYLE
    CHECK (PLAY_STYLE IN ('AGGRESSIVE', 'NORMAL', 'DEFENSIVE'));

COMMENT ON COLUMN TBL_BUILDS.PLAY_STYLE
    IS '플레이스타일: AGGRESSIVE=공격 / NORMAL=일반 / DEFENSIVE=수비';

-- 기존 HARASS_FOCUS 데이터 마이그레이션
UPDATE TBL_BUILDS SET PLAY_STYLE = 'NORMAL' WHERE PLAY_STYLE = 'HARASS_FOCUS';
COMMIT;






















-- ============================================================
-- TBL_BUILDS 변경사항
-- SQL Developer에서 한 블록씩 실행하거나 전체 실행 가능
-- ============================================================

-- ① 기존 CHECK 제약조건 삭제
ALTER TABLE TBL_BUILDS DROP CONSTRAINT CHK_BUILDS_AGGRESSION;

-- ② 기존 데이터 마이그레이션 (CHECK 추가 전에 반드시 먼저 실행)
UPDATE TBL_BUILDS SET AGGRESSION = 'SLOW_MULTI'   WHERE AGGRESSION = 'MIN_MULTI';
UPDATE TBL_BUILDS SET AGGRESSION = 'NORMAL_MULTI' WHERE AGGRESSION = 'MID_MULTI';
UPDATE TBL_BUILDS SET AGGRESSION = 'FAST_MULTI'   WHERE AGGRESSION = 'MAX_MULTI';
COMMIT;

-- ③ DEFAULT 값만 변경 (NOT NULL 재선언 없이)
ALTER TABLE TBL_BUILDS
MODIFY AGGRESSION DEFAULT 'NORMAL_MULTI';

-- ④ 새 CHECK 제약조건 추가
ALTER TABLE TBL_BUILDS
ADD CONSTRAINT CHK_BUILDS_AGGRESSION
    CHECK (AGGRESSION IN ('FAST_MULTI', 'NORMAL_MULTI', 'SLOW_MULTI'));

COMMENT ON COLUMN TBL_BUILDS.AGGRESSION
    IS '멀티 타이밍: FAST_MULTI=빠른멀티 / NORMAL_MULTI=일반멀티 / SLOW_MULTI=느린멀티';

-- ⑤ MAX_BASES 컬럼 추가
ALTER TABLE TBL_BUILDS
ADD MAX_BASES NUMBER(2) DEFAULT 4 NOT NULL;

COMMENT ON COLUMN TBL_BUILDS.MAX_BASES
    IS '최대 기지 수 (본진 포함, 기본값 4 / 저그는 해처리+레어+하이브 합산)';

-- ⑥ PLAY_STYLE CHECK 수정 (구버전 HARASS_FOCUS 제거)
ALTER TABLE TBL_BUILDS DROP CONSTRAINT CHK_BUILDS_PLAY_STYLE;

UPDATE TBL_BUILDS SET PLAY_STYLE = 'NORMAL' WHERE PLAY_STYLE = 'HARASS_FOCUS';
COMMIT;

ALTER TABLE TBL_BUILDS
ADD CONSTRAINT CHK_BUILDS_PLAY_STYLE
    CHECK (PLAY_STYLE IN ('AGGRESSIVE', 'NORMAL', 'DEFENSIVE'));

COMMENT ON COLUMN TBL_BUILDS.PLAY_STYLE
    IS '플레이스타일: AGGRESSIVE=공격 / NORMAL=일반 / DEFENSIVE=수비';
    
    
    
commit;




-- TBL_BUILDS에 FOCUS_ATTACK_TIME 컬럼 추가
ALTER TABLE TBL_BUILDS
ADD FOCUS_ATTACK_TIME NUMBER(5) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN TBL_BUILDS.FOCUS_ATTACK_TIME
    IS '집중 공격 타이밍 (초 단위, 0이면 미설정 — 예: 5분=300)';
    
    commit;