-- =====================================================================
-- MSL (My Star League) 전체 DB 초기화 스크립트
-- [통합본] ORCL2.sql + migration_pve_3v3_bo3.sql
--
-- 전제: DB를 완전히 초기화하고 새로 만든다는 가정하에, 기존 ORCL2.sql에
--       누적되어 있던 모든 ALTER/UPDATE 마이그레이션 결과를 각 테이블의
--       CREATE TABLE 정의에 "최종 상태"로 흡수(flatten)했다.
--       따라서 이 스크립트 한 번만 실행하면 기존 ORCL2.sql을 처음부터
--       끝까지 실행한 것과 동일한 최종 스키마 상태가 된다.
--
-- 이번에 반영된 3:3 BO3 변경사항 (migration_pve_3v3_bo3.sql 내용)
--   1) TBL_PVE_BATTLE_SESSION.SET_RESULTS_DATA CLOB 컬럼을
--      CREATE TABLE 단계부터 포함 (기존 ALTER 중복 제거)
--   2) 경기 체계를 "1세트/2세트/3세트(BO3)" 로 고정
--      - TBL_PVE_SUBSTAGE_MAPS : 세트별 맵 지정을 5개 → 3개로 축소
--      - TBL_PVE_OPPONENTS     : 구(舊) 5세트-1인1조(SET_NUMBER 1~5) 체계를
--        신(新) 3세트 x 3명 = 9슬롯(SET_NUMBER 1~9) 체계로 재배치
--        (1~3번째 슬롯=1세트 출전 3명, 4~6번째=2세트, 7~9번째=3세트)
-- =====================================================================

-- =====================================================================
-- 1. 기존 객체 삭제 (자식 → 부모 순서 무관하게 강제 삭제)
-- =====================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_BATTLE_SESSION CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_OWNED_BUILDS CASCADE CONSTRAINTS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILD_UNITS CASCADE CONSTRAINTS';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILDS CASCADE CONSTRAINTS';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_OPPONENTS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_SUBSTAGE_MAPS CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MAPS CASCADE CONSTRAINTS';                   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_PVE_SUBSTAGE_PROGRESS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_SUBSTAGES CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_PVE_PROGRESS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PVE_ENTRY CASCADE CONSTRAINTS';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MATCH_RECORDS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MATCH_LOGS CASCADE CONSTRAINTS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_OWNED_PLAYERS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PACK_CONTENTS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PACKS CASCADE CONSTRAINTS';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PLAYERS CASCADE CONSTRAINTS';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_USERS CASCADE CONSTRAINTS';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_PLAYER_BUILDS CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLAYER_TRAIT CASCADE CONSTRAINTS';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEAM_MATCHUP_BONUS CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILD_MATCHUP CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_MAP_POINTS CASCADE CONSTRAINTS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_USER_DAILY_MISSIONS CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_DAILY_MISSIONS CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_SCRIPTS CASCADE CONSTRAINTS';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TBL_BUILD_STAT_BONUS CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 시퀀스 삭제
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAYERS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACKS';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACK_CONTENTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_OWNED_PLAYERS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MATCH_LOGS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MATCH_RECORD';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_ENTRY';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_OPPONENTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PVE_BATTLE_SESSION';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BUILDS';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BUILD_UNITS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_OWNED_BUILDS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAYER_BUILDS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAYER_TRAIT';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BUILD_MATCHUP';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAP_POINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DAILY_MISSIONS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SCRIPTS';             EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================================
-- 2. 시퀀스 생성
-- =====================================================================
CREATE SEQUENCE SEQ_PLAYERS            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PACKS              START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PACK_CONTENTS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OWNED_PLAYERS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATCH_RECORD       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_ENTRY          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_OPPONENTS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PVE_BATTLE_SESSION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BUILDS             START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BUILD_UNITS        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OWNED_BUILDS       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PLAYER_TRAIT       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BUILD_MATCHUP      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAP_POINTS         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DAILY_MISSIONS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SCRIPTS            START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================================================
-- 3. 테이블 생성 (모든 ALTER 마이그레이션 결과를 최종 상태로 반영)
-- =====================================================================

-- 1. 사용자
CREATE TABLE TBL_USERS (
    USER_ID     VARCHAR2(50)  PRIMARY KEY,
    USER_PW     VARCHAR2(100) NOT NULL,
    USER_NICK   VARCHAR2(100) NOT NULL,
    CRYSTAL     NUMBER        DEFAULT 0,
    TEAM_NAME   VARCHAR2(100),
    TRAIN_POINT NUMBER        DEFAULT 0
);

-- 2. 선수 마스터 (STAT_MACRO/STAT_MICRO/STAT_LUCK → STAT_HP/STAT_HARASS/STAT_SPEED 로 컬럼명 변경 반영)
CREATE TABLE TBL_PLAYERS (
    PLAYER_SEQ      NUMBER        CONSTRAINT PK_PLAYERS PRIMARY KEY,
    PLAYER_NAME     VARCHAR2(100) NOT NULL,
    RACE            CHAR(1)       NOT NULL CHECK (RACE IN ('T', 'P', 'Z')),
    RARITY          VARCHAR2(10)  NOT NULL CHECK (RARITY IN ('N', 'R', 'SR', 'SSR', 'UR')),
    STAT_ATTACK     NUMBER(3)     DEFAULT 50,
    STAT_DEFENSE    NUMBER(3)     DEFAULT 50,
    STAT_HP         NUMBER(3)     DEFAULT 50,
    STAT_HARASS     NUMBER(3)     DEFAULT 50,
    STAT_SPEED      NUMBER(3)     DEFAULT 50,
    PLAYER_IMG_URL  VARCHAR2(255),
    PLAYER_COST     NUMBER(3)     DEFAULT 10
);

-- 3. 시즌 팩
CREATE TABLE TBL_PACKS (
    PACK_SEQ        NUMBER        CONSTRAINT PK_PACKS PRIMARY KEY,
    PACK_NAME       VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(500),
    COST_CRYSTAL    NUMBER        DEFAULT 0,
    BANNER_IMG_URL  VARCHAR2(255),
    IS_AVAILABLE    CHAR(1)       DEFAULT 'Y' CHECK (IS_AVAILABLE IN ('Y', 'N'))
);

-- 4. 팩 구성 선수 (확률표)
CREATE TABLE TBL_PACK_CONTENTS (
    PACK_CONTENT_SEQ NUMBER       CONSTRAINT PK_PACK_CONTENTS PRIMARY KEY,
    PACK_SEQ         NUMBER       NOT NULL CONSTRAINT FK_PACK_CONTENTS_PACK   REFERENCES TBL_PACKS(PACK_SEQ),
    PLAYER_SEQ       NUMBER       NOT NULL CONSTRAINT FK_PACK_CONTENTS_PLAYER REFERENCES TBL_PLAYERS(PLAYER_SEQ),
    DRAW_PROBABILITY NUMBER(7, 6) NOT NULL CHECK (DRAW_PROBABILITY > 0 AND DRAW_PROBABILITY <= 1),
    CONSTRAINT UK_PACK_PLAYER UNIQUE (PACK_SEQ, PLAYER_SEQ)
);

-- 5. 유저 보유 선수 (CONDITION/WIN_STREAK/ENHANCE_* 컬럼 추가 및 ENHANCE_MACRO 등 컬럼명 변경 반영)
CREATE TABLE TBL_OWNED_PLAYERS (
    OWNED_PLAYER_SEQ       NUMBER       CONSTRAINT PK_OWNED_PLAYERS PRIMARY KEY,
    USER_ID                VARCHAR2(50) NOT NULL CONSTRAINT FK_OWNED_PLAYER_USER   REFERENCES TBL_USERS(USER_ID),
    PLAYER_SEQ             NUMBER       NOT NULL CONSTRAINT FK_OWNED_PLAYER_MASTER REFERENCES TBL_PLAYERS(PLAYER_SEQ),
    CURRENT_ATTACK         NUMBER(3)    DEFAULT NULL,
    CURRENT_DEFENSE        NUMBER(3)    DEFAULT NULL,
    CURRENT_HP             NUMBER(3)    DEFAULT NULL,
    CURRENT_HARASS         NUMBER(3)    DEFAULT NULL,
    CURRENT_SPEED          NUMBER(3)    DEFAULT NULL,
    ACQUIRED_AT            DATE         DEFAULT SYSDATE,
    CURRENT_RARITY         VARCHAR2(10) NOT NULL,
    ACQUIRED_FROM_PACK_SEQ NUMBER       CONSTRAINT FK_OWNED_PLAYER_PACK REFERENCES TBL_PACKS(PACK_SEQ),
    CONDITION              VARCHAR2(10) DEFAULT 'NORMAL' CHECK (CONDITION IN ('PEAK', 'GOOD', 'NORMAL', 'TIRED', 'WORST')),
    WIN_STREAK             NUMBER(3)    DEFAULT 0,
    ENHANCE_LEVEL          NUMBER(2)    DEFAULT 0,
    ENHANCE_ATTACK         NUMBER       DEFAULT 0,
    ENHANCE_DEFENSE        NUMBER       DEFAULT 0,
    ENHANCE_HP             NUMBER       DEFAULT 0,
    ENHANCE_HARASS         NUMBER       DEFAULT 0,
    ENHANCE_SPEED          NUMBER       DEFAULT 0,
    ENHANCE_STREAK         NUMBER       DEFAULT 0
);

-- 6. 경기 기록
CREATE TABLE TBL_MATCH_RECORDS (
    MATCH_SEQ        NUMBER       CONSTRAINT PK_MATCH_RECORDS PRIMARY KEY,
    OWNED_PLAYER_SEQ NUMBER       NOT NULL CONSTRAINT FK_MATCH_RECORDS_OWNED REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    MATCH_TYPE       VARCHAR2(20) DEFAULT 'PVE',
    OPPONENT_NAME    VARCHAR2(100),
    OPPONENT_RACE    VARCHAR2(10),
    MAP_NAME         VARCHAR2(100),
    IS_WIN           CHAR(1)      NOT NULL CHECK (IS_WIN IN ('Y', 'N')),
    MATCH_DATE       DATE         DEFAULT SYSDATE
);

-- 7. PVE 엔트리 (1군) : SLOT_NUMBER 범위 1~7 → 1~9 로 확장 (3:3 BO3, 세트당 3명 x 3세트 = 9슬롯)
--    + FK에 ON DELETE CASCADE 반영
CREATE TABLE TBL_PVE_ENTRY (
    PVE_ENTRY_SEQ    NUMBER       CONSTRAINT PK_PVE_ENTRY PRIMARY KEY,
    USER_ID          VARCHAR2(50) NOT NULL CONSTRAINT FK_PVE_ENTRY_USER         REFERENCES TBL_USERS(USER_ID),
    OWNED_PLAYER_SEQ NUMBER       NOT NULL CONSTRAINT FK_PVE_ENTRY_OWNED_PLAYER REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    SLOT_NUMBER      NUMBER(1)    NOT NULL CONSTRAINT CHK_PVE_SLOT_NUM CHECK (SLOT_NUMBER BETWEEN 1 AND 9),
    CONSTRAINT UK_USER_SLOT         UNIQUE (USER_ID, SLOT_NUMBER),
    CONSTRAINT UK_USER_OWNED_PLAYER UNIQUE (USER_ID, OWNED_PLAYER_SEQ)
);

-- 8. PVE 메인 진행
CREATE TABLE USER_PVE_PROGRESS (
    USER_ID      VARCHAR2(50) NOT NULL,
    STAGE_LEVEL  NUMBER       NOT NULL,
    STAGE_STATUS VARCHAR2(20) NOT NULL,
    UPDATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PVE_PROGRESS     PRIMARY KEY (USER_ID, STAGE_LEVEL),
    CONSTRAINT FK_USER_PVE_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_USER_PVE_STATUS       CHECK (STAGE_STATUS IN ('CLEARED', 'IN_PROGRESS', 'LOCKED'))
);

-- 9. PVE 서브스테이지 마스터
CREATE TABLE TBL_PVE_SUBSTAGES (
    STAGE_LEVEL        NUMBER        NOT NULL,
    SUB_LEVEL          NUMBER        NOT NULL,
    SUB_TITLE          VARCHAR2(100) NOT NULL,
    OPPONENT_TEAM_NAME VARCHAR2(100),
    CONSTRAINT PK_PVE_SUBSTAGES PRIMARY KEY (STAGE_LEVEL, SUB_LEVEL)
);

-- 10. 사용자 서브스테이지 진행
CREATE TABLE USER_PVE_SUBSTAGE_PROGRESS (
    USER_ID     VARCHAR2(50) NOT NULL,
    STAGE_LEVEL NUMBER       NOT NULL,
    SUB_LEVEL   NUMBER       NOT NULL,
    IS_CLEARED  CHAR(1)      DEFAULT 'Y' NOT NULL CHECK (IS_CLEARED = 'Y'),
    CLEARED_AT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_PVE_SUBSTAGE       PRIMARY KEY (USER_ID, STAGE_LEVEL, SUB_LEVEL),
    CONSTRAINT FK_USER_PVE_SUBSTAGE_USER   FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_PVE_SUBSTAGE_MASTER FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE
);
CREATE INDEX IDX_USER_PVE_SUBSTAGE_USER ON USER_PVE_SUBSTAGE_PROGRESS (USER_ID, STAGE_LEVEL);

-- 11. 맵 마스터 (MAP_IMG_URL 컬럼 추가 반영)
CREATE TABLE TBL_MAPS (
    MAP_ID      VARCHAR2(50)   CONSTRAINT PK_MAPS PRIMARY KEY,
    MAP_NAME    VARCHAR2(100)  NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    WIN_RATE_T  NUMBER(5, 2)   DEFAULT 50.00,
    WIN_RATE_P  NUMBER(5, 2)   DEFAULT 50.00,
    WIN_RATE_Z  NUMBER(5, 2)   DEFAULT 50.00,
    MAP_IMG_URL VARCHAR2(500)
);

-- 12. PVE 서브스테이지별 맵 : 3:3 BO3 체계 → SET_NUMBER 는 실제 경기 세트(1~3)만 사용
--     + FK에 ON DELETE CASCADE 반영
CREATE TABLE TBL_PVE_SUBSTAGE_MAPS (
    STAGE_LEVEL NUMBER       NOT NULL,
    SUB_LEVEL   NUMBER       NOT NULL,
    SET_NUMBER  NUMBER(1)    NOT NULL,
    MAP_ID      VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PVE_SUBSTAGE_MAPS    PRIMARY KEY (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER),
    CONSTRAINT FK_SUBSTAGE_MAPS_MASTER FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE,
    CONSTRAINT FK_SUBSTAGE_MAPS_MAP    FOREIGN KEY (MAP_ID) REFERENCES TBL_MAPS(MAP_ID) ON DELETE CASCADE
);
COMMENT ON COLUMN TBL_PVE_SUBSTAGE_MAPS.SET_NUMBER IS '실제 경기 세트 번호 (1~3, BO3). TBL_PVE_OPPONENTS.SET_NUMBER(1~9 슬롯)와는 다른 개념.';

-- 13. 빌드 마스터 (TECH_STYLE/EXPAND_STYLE 컬럼 제거, MAX_BASES/FOCUS_ATTACK_TIME/HARASS_STYLE/
--     PREFERRED_BUILDINGS/BUILD_PRESET/WIN_COUNT/LOSE_COUNT 추가, RACE/VS_RACE VARCHAR2(10)로 변경,
--     VS_RACE NULL 허용 및 체크 제거, USER_ID FK 제거(SYSTEM 빌드 지원), PLAY_STYLE/AGGRESSION
--     체크 값 최종본 반영 — 모두 최종 상태로 흡수)
CREATE TABLE TBL_BUILDS (
    BUILD_ID            NUMBER        CONSTRAINT PK_BUILDS PRIMARY KEY,
    USER_ID             VARCHAR2(50),
    BUILD_NAME          VARCHAR2(100) NOT NULL,
    RACE                VARCHAR2(10)  NOT NULL CONSTRAINT CHK_BUILDS_RACE CHECK (RACE IN ('T', 'P', 'Z')),
    VS_RACE             VARCHAR2(10)  NULL,
    PLAY_STYLE          VARCHAR2(15)  DEFAULT 'AGGRESSIVE' NOT NULL
                                       CONSTRAINT CHK_BUILDS_PLAY_STYLE
                                       CHECK (PLAY_STYLE IN ('AGGRESSIVE', 'NORMAL', 'DEFENSIVE')),
    AGGRESSION          VARCHAR2(15)  DEFAULT 'NORMAL_MULTI' NOT NULL
                                       CONSTRAINT CHK_BUILDS_AGGRESSION
                                       CHECK (AGGRESSION IN ('FAST_MULTI', 'NORMAL_MULTI', 'SLOW_MULTI')),
    MAX_TIER            NUMBER(1)     DEFAULT 3 NOT NULL
                                       CONSTRAINT CHK_BUILDS_MAX_TIER
                                       CHECK (MAX_TIER IN (1, 2, 3)),
    MAX_BASES           NUMBER(2)     DEFAULT 4 NOT NULL,
    FOCUS_ATTACK_TIME   NUMBER(5)     DEFAULT 0 NOT NULL,
    HARASS_STYLE        VARCHAR2(20)  DEFAULT 'NORMAL_HARASS'
                                       CONSTRAINT CK_BUILDS_HARASS_STYLE
                                       CHECK (HARASS_STYLE IN ('NO_HARASS', 'NORMAL_HARASS', 'HEAVY_HARASS')),
    PREFERRED_BUILDINGS VARCHAR2(500),
    BUILD_PRESET        VARCHAR2(100),
    WIN_COUNT           NUMBER        DEFAULT 0,
    LOSE_COUNT          NUMBER        DEFAULT 0,
    SCRIPT_CONTENT      CLOB,
    CREATED_AT          DATE          DEFAULT SYSDATE,
    CONSTRAINT UK_USER_BUILD_NAME_RACE UNIQUE (USER_ID, BUILD_NAME, RACE, VS_RACE)
);
COMMENT ON COLUMN TBL_BUILDS.PLAY_STYLE   IS '플레이스타일: AGGRESSIVE=공격 / NORMAL=일반 / DEFENSIVE=방어';
COMMENT ON COLUMN TBL_BUILDS.AGGRESSION   IS '확장성향: FAST_MULTI=빠른멀티 / NORMAL_MULTI=일반멀티 / SLOW_MULTI=느린멀티';
COMMENT ON COLUMN TBL_BUILDS.MAX_TIER     IS '최대 티어: 1=1티어만 / 2=1~2티어 / 3=전체(기본)';
COMMENT ON COLUMN TBL_BUILDS.HARASS_STYLE IS '견제 성향: NO_HARASS(견제없음) / NORMAL_HARASS(일반견제, 2~6회) / HEAVY_HARASS(강한견제, 7~11회)';

-- 14. 페이즈별 유닛 구성
CREATE TABLE TBL_BUILD_UNITS (
    BUILD_UNIT_ID NUMBER       CONSTRAINT PK_BUILD_UNITS PRIMARY KEY,
    BUILD_ID      NUMBER       NOT NULL CONSTRAINT FK_BU_BUILD REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    PHASE         VARCHAR2(10) NOT NULL CHECK (PHASE IN ('EARLY', 'MID', 'LATE')),
    UNIT_ID       VARCHAR2(50) NOT NULL,
    PRIORITY      NUMBER(1)    DEFAULT 1 NOT NULL CHECK (PRIORITY BETWEEN 1 AND 5),
    CONSTRAINT UK_BUILD_PHASE_UNIT UNIQUE (BUILD_ID, PHASE, UNIT_ID)
);
COMMENT ON COLUMN TBL_BUILD_UNITS.PRIORITY IS '1=최우선(가장많이생산) ~ 5=보조';

-- 15. 선수-빌드 연결
CREATE TABLE TBL_OWNED_BUILDS (
    OWNED_BUILD_SEQ NUMBER NOT NULL CONSTRAINT PK_OWNED_BUILDS PRIMARY KEY,
    PLAYER_SEQ      NUMBER NOT NULL CONSTRAINT FK_OB_PLAYER REFERENCES TBL_OWNED_PLAYERS(OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    BUILD_ID        NUMBER NOT NULL CONSTRAINT FK_OB_BUILD  REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    CONSTRAINT UK_PLAYER_BUILD UNIQUE (PLAYER_SEQ, BUILD_ID)
);
COMMENT ON TABLE TBL_OWNED_BUILDS IS '보유선수(OWNED_PLAYER)가 사용하는 빌드 연결';

-- 16. PVE AI 엔트리 : 구 BUILD_ID 단일 컬럼 제거 → 상대 종족별 빌드(BUILD_ID_VS_T/Z/P) 3개로 분리.
--     SET_NUMBER 는 3:3 BO3 슬롯(1~9) 의미로 사용 (1~3=1세트 출전 3명, 4~6=2세트, 7~9=3세트)
CREATE TABLE TBL_PVE_OPPONENTS (
    OPPONENT_ID   NUMBER    CONSTRAINT PK_PVE_OPPONENTS PRIMARY KEY,
    STAGE_LEVEL   NUMBER    NOT NULL,
    SUB_LEVEL     NUMBER    NOT NULL,
    PLAYER_SEQ    NUMBER    NOT NULL,
    SET_NUMBER    NUMBER(1) NULL,
    BUILD_ID_VS_T NUMBER    NULL,
    BUILD_ID_VS_Z NUMBER    NULL,
    BUILD_ID_VS_P NUMBER    NULL,
    CONSTRAINT FK_PVE_OPPONENTS_SUBSTAGE FOREIGN KEY (STAGE_LEVEL, SUB_LEVEL) REFERENCES TBL_PVE_SUBSTAGES(STAGE_LEVEL, SUB_LEVEL) ON DELETE CASCADE,
    CONSTRAINT FK_PVE_OPPONENTS_PLAYER   FOREIGN KEY (PLAYER_SEQ) REFERENCES TBL_PLAYERS(PLAYER_SEQ),
    CONSTRAINT FK_OPP_BUILD_VS_T         FOREIGN KEY (BUILD_ID_VS_T) REFERENCES TBL_BUILDS(BUILD_ID),
    CONSTRAINT FK_OPP_BUILD_VS_Z         FOREIGN KEY (BUILD_ID_VS_Z) REFERENCES TBL_BUILDS(BUILD_ID),
    CONSTRAINT FK_OPP_BUILD_VS_P         FOREIGN KEY (BUILD_ID_VS_P) REFERENCES TBL_BUILDS(BUILD_ID)
);
COMMENT ON COLUMN TBL_PVE_OPPONENTS.SET_NUMBER IS '3:3 BO3 슬롯 번호 (1~9): 1~3번째=1세트 출전 3명, 4~6번째=2세트, 7~9번째=3세트';

-- 17. PVE 배틀 세션 : SET_RESULTS_DATA CLOB 컬럼을 생성 시점부터 포함 (migration_pve_3v3_bo3.sql 반영)
CREATE TABLE TBL_PVE_BATTLE_SESSION (
    BATTLE_ID         NUMBER        CONSTRAINT PK_PVE_BATTLE_SESSION PRIMARY KEY,
    USER_ID           VARCHAR2(50)  NOT NULL,
    STAGE_LEVEL       NUMBER        NOT NULL,
    SUB_LEVEL         NUMBER        NOT NULL,
    MATCHUP_DATA      CLOB,
    MY_TEAM_DATA      CLOB,
    AI_TEAM_DATA      CLOB,
    GAME_STATE_DATA   CLOB,
    SET_RESULTS_DATA  CLOB,
    CREATED_AT        TIMESTAMP     DEFAULT SYSDATE,
    STATUS            VARCHAR2(20)  DEFAULT 'IN_PROGRESS' CHECK (STATUS IN ('IN_PROGRESS', 'COMPLETED')),
    MY_WINS           NUMBER        DEFAULT 0,
    AI_WINS           NUMBER        DEFAULT 0,
    CURRENT_SET       NUMBER        DEFAULT 1,
    CONSTRAINT UK_PVE_ACTIVE_BATTLE UNIQUE (USER_ID, STAGE_LEVEL, SUB_LEVEL, STATUS)
);
COMMENT ON COLUMN TBL_PVE_BATTLE_SESSION.MY_TEAM_DATA     IS '3:3 BO3 내 엔트리 JSON 배열: [[set1P1,set1P2,set1P3],[set2P1,set2P2,set2P3],[set3P1,set3P2,set3P3]] (각 값은 OWNED_PLAYER_SEQ)';
COMMENT ON COLUMN TBL_PVE_BATTLE_SESSION.AI_TEAM_DATA     IS '현재는 DB 재조회로 충분하여 미사용. 향후 AI 엔트리도 세션에 고정 저장 시 MY_TEAM_DATA와 동일한 형태로 사용 가능.';
COMMENT ON COLUMN TBL_PVE_BATTLE_SESSION.SET_RESULTS_DATA IS '완료된 세트별 결과 누적 JSON 배열 예: [{"setNumber":1,"winner":"blue"},{"setNumber":2,"winner":"red"}]';
COMMENT ON COLUMN TBL_PVE_BATTLE_SESSION.CURRENT_SET      IS '현재 진행 중인 세트 번호 (1~3, BO3)';

-- 18. 대본 시스템
CREATE TABLE TBL_SCRIPTS (
    SCRIPT_ID    NUMBER       CONSTRAINT PK_SCRIPTS PRIMARY KEY,
    MY_BUILD_ID  NUMBER       NOT NULL CONSTRAINT FK_SC_MY  REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    OPP_BUILD_ID NUMBER       NOT NULL CONSTRAINT FK_SC_OPP REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    RESULT       VARCHAR2(10) NOT NULL CHECK (RESULT IN ('WIN','LOSE')),
    CONTENT      CLOB         NOT NULL,
    CREATED_AT   DATE         DEFAULT SYSDATE,
    CONSTRAINT UK_SCRIPTS UNIQUE (MY_BUILD_ID, OPP_BUILD_ID, RESULT)
);

-- 19. 빌드 상호 매치업
CREATE TABLE TBL_BUILD_MATCHUP (
    MATCHUP_ID NUMBER       CONSTRAINT PK_BUILD_MATCHUP PRIMARY KEY,
    BUILD_ID_A NUMBER       NOT NULL CONSTRAINT FK_BM_BUILD_A REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    BUILD_ID_B NUMBER       NOT NULL CONSTRAINT FK_BM_BUILD_B REFERENCES TBL_BUILDS(BUILD_ID) ON DELETE CASCADE,
    MATCHUP    VARCHAR2(10) NOT NULL CHECK (MATCHUP IN ('GOOD','NORMAL','BAD')),
    CONSTRAINT UK_BUILD_VS_BUILD UNIQUE (BUILD_ID_A, BUILD_ID_B)
);

-- 20. 맵 포인트 (스폰/지점 좌표)
CREATE TABLE TBL_MAP_POINTS (
    POINT_ID    NUMBER          CONSTRAINT PK_MAP_POINTS PRIMARY KEY,
    MAP_ID      VARCHAR2(50)    NOT NULL,
    POINT_NAME  VARCHAR2(100)   NOT NULL,
    POINT_TYPE  VARCHAR2(50)    DEFAULT 'STARTING',
    PIXEL_X     NUMBER          NOT NULL,
    PIXEL_Y     NUMBER          NOT NULL,
    CONSTRAINT FK_MAP_POINTS_MAP FOREIGN KEY (MAP_ID) REFERENCES TBL_MAPS(MAP_ID) ON DELETE CASCADE
);

-- 21. 팀 조합 상성 보너스 (3:3 종족 조합, 예: 'TTT','PPP' 등 3자리 = 3명 팀)
CREATE TABLE TEAM_MATCHUP_BONUS (
    MATCHUP_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MY_TEAM_COMBO    VARCHAR2(3)   NOT NULL,
    OPP_TEAM_COMBO   VARCHAR2(3)   NOT NULL,
    BONUS_MULTIPLIER NUMBER(4,2)   DEFAULT 1.0 NOT NULL,
    DESCRIPTION      VARCHAR2(200),
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_TEAM_MATCHUP UNIQUE (MY_TEAM_COMBO, OPP_TEAM_COMBO)
);

-- 22. 일일 미션 마스터
CREATE TABLE TBL_DAILY_MISSIONS (
    MISSION_ID          NUMBER CONSTRAINT PK_DAILY_MISSIONS PRIMARY KEY,
    MISSION_TYPE        VARCHAR2(50) NOT NULL,
    MISSION_TITLE       VARCHAR2(200) NOT NULL,
    MISSION_DESC        VARCHAR2(500),
    TARGET_COUNT        NUMBER DEFAULT 1,
    REWARD_CRYSTAL      NUMBER DEFAULT 0,
    REWARD_EXP          NUMBER DEFAULT 0,
    MISSION_ICON        VARCHAR2(50),
    DISPLAY_ORDER       NUMBER DEFAULT 0,
    IS_ACTIVE           CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT          DATE DEFAULT SYSDATE
);

-- 23. 사용자 일일 미션 진행
CREATE TABLE TBL_USER_DAILY_MISSIONS (
    USER_ID             VARCHAR2(50) NOT NULL,
    MISSION_ID          NUMBER NOT NULL,
    CURRENT_COUNT       NUMBER DEFAULT 0,
    IS_COMPLETED        CHAR(1) DEFAULT 'N' CHECK (IS_COMPLETED IN ('Y', 'N')),
    IS_CLAIMED          CHAR(1) DEFAULT 'N' CHECK (IS_CLAIMED IN ('Y', 'N')),
    COMPLETED_AT        DATE,
    CLAIMED_AT          DATE,
    RESET_DATE          DATE DEFAULT TRUNC(SYSDATE),
    CONSTRAINT PK_USER_DAILY_MISSIONS PRIMARY KEY (USER_ID, MISSION_ID),
    CONSTRAINT FK_USER_DAILY_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_DAILY_MISSION FOREIGN KEY (MISSION_ID) REFERENCES TBL_DAILY_MISSIONS(MISSION_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_USER_DAILY_RESET ON TBL_USER_DAILY_MISSIONS(USER_ID, RESET_DATE);
CREATE INDEX IDX_DAILY_MISSION_TYPE ON TBL_DAILY_MISSIONS(MISSION_TYPE);

-- 24. 선수 성향(트레잇)
CREATE TABLE PLAYER_TRAIT (
    TRAIT_SEQ          NUMBER         NOT NULL,
    OWNED_PLAYER_SEQ   NUMBER         NOT NULL,
    ATK_WEIGHT         NUMBER(2)      DEFAULT 5 NOT NULL,
    DEF_WEIGHT         NUMBER(2)      DEFAULT 5 NOT NULL,
    ASSIST_WEIGHT      NUMBER(2)      DEFAULT 3 NOT NULL,
    HARASS_WEIGHT      NUMBER(2)      DEFAULT 3 NOT NULL,
    TRAIT_LEVEL        NUMBER(1)      DEFAULT 1 NOT NULL,
    CREATED_AT         DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT         DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PLAYER_TRAIT       PRIMARY KEY (TRAIT_SEQ),
    CONSTRAINT FK_TRAIT_OWNED_PLAYER FOREIGN KEY (OWNED_PLAYER_SEQ) REFERENCES TBL_OWNED_PLAYERS (OWNED_PLAYER_SEQ) ON DELETE CASCADE,
    CONSTRAINT UQ_TRAIT_PLAYER       UNIQUE (OWNED_PLAYER_SEQ),
    CONSTRAINT CHK_ATK_WEIGHT        CHECK (ATK_WEIGHT    BETWEEN 1 AND 10),
    CONSTRAINT CHK_DEF_WEIGHT        CHECK (DEF_WEIGHT    BETWEEN 1 AND 10),
    CONSTRAINT CHK_ASSIST_WEIGHT     CHECK (ASSIST_WEIGHT BETWEEN 1 AND 10),
    CONSTRAINT CHK_HARASS_WEIGHT     CHECK (HARASS_WEIGHT BETWEEN 1 AND 10),
    CONSTRAINT CHK_TRAIT_LEVEL       CHECK (TRAIT_LEVEL   BETWEEN 1 AND 5)
);

-- =====================================================================
-- 4. 트리거 생성
-- =====================================================================

CREATE OR REPLACE TRIGGER TRG_PVE_BATTLE_SESSION_PK
BEFORE INSERT ON TBL_PVE_BATTLE_SESSION FOR EACH ROW
WHEN (NEW.BATTLE_ID IS NULL)
BEGIN SELECT SEQ_PVE_BATTLE_SESSION.NEXTVAL INTO :NEW.BATTLE_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_BUILDS_PK
BEFORE INSERT ON TBL_BUILDS FOR EACH ROW
WHEN (NEW.BUILD_ID IS NULL)
BEGIN SELECT SEQ_BUILDS.NEXTVAL INTO :NEW.BUILD_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_BUILD_UNITS_PK
BEFORE INSERT ON TBL_BUILD_UNITS FOR EACH ROW
WHEN (NEW.BUILD_UNIT_ID IS NULL)
BEGIN SELECT SEQ_BUILD_UNITS.NEXTVAL INTO :NEW.BUILD_UNIT_ID FROM DUAL; END;
/

CREATE OR REPLACE TRIGGER TRG_OWNED_BUILDS_PK
BEFORE INSERT ON TBL_OWNED_BUILDS FOR EACH ROW
WHEN (NEW.OWNED_BUILD_SEQ IS NULL)
BEGIN SELECT SEQ_OWNED_BUILDS.NEXTVAL INTO :NEW.OWNED_BUILD_SEQ FROM DUAL; END;
/

-- =====================================================================
-- 5. 일일 미션 리셋 프로시저
-- =====================================================================
CREATE OR REPLACE PROCEDURE RESET_DAILY_MISSIONS AS
BEGIN
    DELETE FROM TBL_USER_DAILY_MISSIONS WHERE RESET_DATE < TRUNC(SYSDATE);
    COMMIT;
END;
/

-- =====================================================================
-- 6. 마스터 데이터 삽입
-- =====================================================================

INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser1',  '1234', '테스터1',  1000, 'TestUser1');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser2',  '1234', '테스터2',  1000, 'TestUser2');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser3',  '1234', '테스터3',  1000, 'TestUser3');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser4',  '1234', '테스터4',  1000, 'TestUser4');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser5',  '1234', '테스터5',  1000, 'TestUser5');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser6',  '1234', '테스터6',  1000, 'TestUser6');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser7',  '1234', '테스터7',  1000, 'TestUser7');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser8',  '1234', '테스터8',  1000, 'TestUser8');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser9',  '1234', '테스터9',  1000, 'TestUser9');
INSERT INTO TBL_USERS (USER_ID, USER_PW, USER_NICK, CRYSTAL, TEAM_NAME) VALUES ('testuser10', '1234', '테스터10', 1000, 'TestUser10');

INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '금선2',    'T', 'SR',  17, 64, 25, 15, 13, '/image/players/geumseon2.png',   5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '요닝',     'Z', 'SR',  13, 31, 13, 16, 61, '/image/players/yoning.png',       5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '슬아',     'Z', 'SR',  35, 22, 11, 27, 45, '/image/players/sulah.png',        5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '빵리나',   'P', 'SR',  25, 42, 25, 21, 24, '/image/players/bbangrina.png',    5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '카히리',   'Z', 'SR',  15, 21, 31, 50, 17, '/image/players/kahiri.png',       5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '지두두',   'T', 'SR',  40, 31, 39, 15, 12, '/image/players/jidudu.png',       5);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '서지수',   'T', 'UR',  38, 44, 40, 33, 35, '/image/players/seojisu.png',      10);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '보혜',     'P', 'UR',  40, 35, 40, 30, 40, '/image/players/bohye.png',        10);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '다린',     'T', 'SSR', 32, 30, 32, 30, 32, '/image/players/darin.png',        7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '애공',     'P', 'SSR', 32, 30, 32, 30, 32, '/image/players/aegong.png',       7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '혜로로',   'Z', 'SSR', 32, 30, 32, 30, 32, '/image/players/hyeroro.png',      7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '우힝이',   'T', 'SSR', 32, 30, 32, 30, 32, '/image/players/woohinge.png',     7);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '꼬니부깅', 'P', 'R',   22, 22, 22, 22, 22, '/image/players/ggonibuking.png',  3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '묘아',     'P', 'R',   22, 22, 22, 22, 22, '/image/players/myoah.png',        3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '아라미',   'Z', 'R',   22, 22, 22, 22, 22, '/image/players/ahrami.png',       3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '뽀누나',   'T', 'R',   22, 22, 22, 22, 22, '/image/players/bbonuna.png',      3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '하두링',   'P', 'R',   22, 22, 22, 22, 22, '/image/players/haduring.png',     3);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '모리',     'T', 'N',   20, 20, 20, 20, 10, '/image/players/mori.png',         1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '2라니',    'Z', 'N',   20, 20, 20, 20, 10, '/image/players/2rani.png',        1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '선정은',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/sunjungeun.png',   1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '비타밍',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/vitaming.png',     1);
INSERT INTO TBL_PLAYERS (PLAYER_SEQ, PLAYER_NAME, RACE, RARITY, STAT_ATTACK, STAT_DEFENSE, STAT_HP, STAT_HARASS, STAT_SPEED, PLAYER_IMG_URL, PLAYER_COST) VALUES (SEQ_PLAYERS.NEXTVAL, '정다닝',   'T', 'N',   20, 20, 20, 20, 10, '/image/players/jungdaning.png',   1);

INSERT INTO TBL_PACKS (PACK_SEQ, PACK_NAME, DESCRIPTION, COST_CRYSTAL, BANNER_IMG_URL, IS_AVAILABLE) VALUES (SEQ_PACKS.NEXTVAL, '마이 여캠 스타리그 출시팩 1', '마이 여캠 스타리그 출시 기념 첫번째 팩입니다!', 100, '/image/mystarleague_1pack.png', 'Y');
INSERT INTO TBL_PACKS (PACK_SEQ, PACK_NAME, DESCRIPTION, COST_CRYSTAL, BANNER_IMG_URL, IS_AVAILABLE) VALUES (SEQ_PACKS.NEXTVAL, '마이 여캠 스타리그 출시팩 2', '마이 여캠 스타리그 출시 기념 두 번째 팩입니다',  100, '/image/mystarleague_2pack.png', 'Y');

INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  7, 0.010000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  9, 0.015000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 10, 0.015000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  1, 0.016666);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  2, 0.016666);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1,  3, 0.016668);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 13, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 14, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 15, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 16, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 17, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 18, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 19, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 20, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 21, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 1, 22, 0.122000);

INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  8, 0.010000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 11, 0.015000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 12, 0.015000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  4, 0.016666);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  5, 0.016666);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2,  6, 0.016668);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 13, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 14, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 15, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 16, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 17, 0.060000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 18, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 19, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 20, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 21, 0.122000);
INSERT INTO TBL_PACK_CONTENTS (PACK_CONTENT_SEQ, PACK_SEQ, PLAYER_SEQ, DRAW_PROBABILITY) VALUES (SEQ_PACK_CONTENTS.NEXTVAL, 2, 22, 0.122000);

INSERT INTO TBL_PVE_SUBSTAGES (STAGE_LEVEL, SUB_LEVEL, SUB_TITLE, OPPONENT_TEAM_NAME) VALUES (1, 1, '오프닝 매치 : 빛의 개막전', '프로리그 등록 예선 첫 경기.');

INSERT INTO TBL_MAPS (MAP_ID, MAP_NAME, DESCRIPTION, WIN_RATE_T, WIN_RATE_P, WIN_RATE_Z) VALUES ('fighting_spirit', 'fighting_spirit', '2인용 맵. 전략적인 초반 빌드와 컨트롤이 승패를 가릅니다.', 50.00, 50.00, 50.00);

-- 3:3 BO3 : 세트는 1/2/3 세 개만 존재 (5세트 → 3세트로 축소)
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 1, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 2, 'fighting_spirit');
INSERT INTO TBL_PVE_SUBSTAGE_MAPS (STAGE_LEVEL, SUB_LEVEL, SET_NUMBER, MAP_ID) VALUES (1, 1, 3, 'fighting_spirit');

-- 3:3 BO3 : 9슬롯(1세트 3명 + 2세트 3명 + 3세트 3명) 배치 (구 5세트-1인1조 체계 → 신 체계로 재배치)
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 18, 1);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 19, 2);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 14, 3);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1,  5, 4);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 22, 5);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 11, 6);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1,  9, 7);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1, 16, 8);
INSERT INTO TBL_PVE_OPPONENTS (OPPONENT_ID, STAGE_LEVEL, SUB_LEVEL, PLAYER_SEQ, SET_NUMBER) VALUES (SEQ_PVE_OPPONENTS.NEXTVAL, 1, 1,  7, 9);

INSERT INTO TEAM_MATCHUP_BONUS (MY_TEAM_COMBO, OPP_TEAM_COMBO, BONUS_MULTIPLIER, DESCRIPTION) VALUES ('TTT', 'ZZZ', 1.20, '테란 3명 vs 저그 3명 : 테란 유리');
INSERT INTO TEAM_MATCHUP_BONUS (MY_TEAM_COMBO, OPP_TEAM_COMBO, BONUS_MULTIPLIER, DESCRIPTION) VALUES ('TTT', 'PPP', 0.85, '테란 3명 vs 프로토스 3명 : 테란 불리');
INSERT INTO TEAM_MATCHUP_BONUS (MY_TEAM_COMBO, OPP_TEAM_COMBO, BONUS_MULTIPLIER, DESCRIPTION) VALUES ('ZZZ', 'PPP', 1.15, '저그 3명 vs 프로토스 3명 : 저그 유리');
INSERT INTO TEAM_MATCHUP_BONUS (MY_TEAM_COMBO, OPP_TEAM_COMBO, BONUS_MULTIPLIER, DESCRIPTION) VALUES ('PPP', 'TTT', 1.20, '프로토스 3명 vs 테란 3명 : 프토 유리');
INSERT INTO TEAM_MATCHUP_BONUS (MY_TEAM_COMBO, OPP_TEAM_COMBO, BONUS_MULTIPLIER, DESCRIPTION) VALUES ('TTZ', 'PPP', 1.10, '테란2저그1 vs 프로토스 3명');

INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'PVE_WIN',     '라운드 클리어', 'PVE 라운드 1회 클리어하기',        1, 50,  100, '🏆', 1);
INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'PVE_PERFECT', '완벽한 승리',   '3승0패로 라운드 클리어하기',       3, 100, 150, '⚔️', 2);
INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'TRAIN',       '선수 훈련',     '선수 훈련 1회 진행하기',          1, 200, 300, '💪', 3);
INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'GACHA',       '스카우팅',      '선수 영입 1회 진행하기 (1회/10회 모두 가능)', 1, 30, 50, '🌟', 4);
INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'ENHANCE',     '선수 육성',     '선수 1회 강화하기',               1, 50,  80,  '⚡', 5);
INSERT INTO TBL_DAILY_MISSIONS (MISSION_ID, MISSION_TYPE, MISSION_TITLE, MISSION_DESC, TARGET_COUNT, REWARD_CRYSTAL, REWARD_EXP, MISSION_ICON, DISPLAY_ORDER) VALUES (SEQ_DAILY_MISSIONS.NEXTVAL, 'LOGIN',       '출석 체크',     '오늘 접속하기',                   1, 20,  50,  '📅', 6);

COMMIT;
